version: '3.8'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=alfred_db
      - POSTGRES_USER=alfred_user
      - POSTGRES_PASSWORD=alfred_pass
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U alfred_user -d alfred_db -h localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: >
      sh -c "python manage.py migrate && 
             python manage.py seed_data &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app 
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=alfred_db
      - DB_USER=alfred_user
      - DB_PASSWORD=alfred_pass

volumes:
  postgres_data: 